# Internal miwear Makefile - not included in open source release

ifeq ($(CONFIG_QUICKAPP_MIWEAR),y)
EXPORT_FILES += proprietary/miwear/ajs_porting.h
EXPORT_FILES += proprietary/miwear/app_manager.h
endif
